### ISSUE TITLE
头文件导不进去

### ISSUE THREAD

**Issue by luohaohaha** [neverwoodsS/flutter_qq_bridge#1]
pub.flutter-io.cn/flutter_qq_bridge-0.0.1/ios/Classes/FlutterQqBridgePlugin.h:2:9: fatal error: 'TencentOpenAPI/TencentOAuth.h' file not found
    #import <TencentOpenAPI/TencentOAuth.h>

XCode 9.3，这个怎么解

**Comment by llearn** [comment]
因为iOS库端他没有包含TencentOpenAPI.framework。我提交了PR，没有合并，你可以暂时这么引用依赖， 或者自己手动引用T encentOpenAPI.framework
```
dependencies:
    flutter_qq_bridge:
        git: git://github.com/llearn/flutter_qq_bridge.git
```

**Comment by neverwoodsS** [comment]
因为 TencentOpenAPI.framework 文件较大，我个人在 xcode 里面也试过，不管我插件带不带 framework，最后的项目里也还是要添加这个依赖的。加上 pub 上的建议是插件大小越小越好，所以当时特意没有放进去。PR 我还是合并了，过会更新0.0.2
